name: gym
description: A new Flutter project.
publish_to: 'none'

version: 2.0.3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  intl: ^0.19.0
  flutter_native_splash: ^2.3.2
  image_picker: ^1.0.4
  flutter_polygon: ^0.3.0+2
  horizontal_week_calendar: ^0.0.11
  table_calendar: ^3.0.9
  awesome_notifications_core: ^0.8.0
  awesome_notifications: ^0.8.0
  another_flushbar: ^1.12.30
  video_player: ^2.9.1
  animated_toggle: ^0.1.3
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.2
  no_screenshot: ^0.0.1+6
  url_launcher: ^6.3.0
  talker_dio_logger: ^4.3.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - lang/
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/yousef/
    - assets/images/home/
    - assets/images/icons/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Medium.otf
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
